name: ds_lint
description: Extension of linter rules for altush Flutter projects. Implements imports check, easy_localization, etc
version: 0.1.2
homepage: https://github.com/al-tush/ds_lint

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  analyzer: ^6.4.1
  custom_lint_core: ^0.6.5
  custom_lint_builder: ^0.6.4

  meta: ^1.11.0
  yaml: ^3.1.2


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0